import { sqliteTable, text, integer } from "drizzle-orm/sqlite-core";

export const guides = sqliteTable("guides", {
  id:          text("id").primaryKey(),
  slug:        text("slug").unique().notNull(),
  category:    text("category").notNull(),
  published:   integer("published", { mode: "boolean" }).notNull().default(false),
  price:       text("price").notNull().default(""),
  timeline:    text("timeline").notNull().default(""),
  lastUpdated: text("last_updated").notNull().default(""),
  createdAt:   text("created_at").notNull(),
  updatedAt:   text("updated_at").notNull(),

  enTitle:    text("en_title").notNull().default(""),
  enSummary:  text("en_summary").notNull().default(""),
  enAudience: text("en_audience").notNull().default(""),
  enOverview: text("en_overview").notNull().default(""),

  ruTitle:    text("ru_title").notNull().default(""),
  ruSummary:  text("ru_summary").notNull().default(""),
  ruAudience: text("ru_audience").notNull().default(""),
  ruOverview: text("ru_overview").notNull().default(""),
});

export const steps = sqliteTable("steps", {
  id:        text("id").primaryKey(),
  guideId:   text("guide_id").notNull().references(() => guides.id, { onDelete: "cascade" }),
  stepOrder: integer("step_order").notNull(),
  cost:      text("cost").notNull().default(""),
  timeEst:   text("time_est").notNull().default(""),

  enTitle:   text("en_title").notNull().default(""),
  enWhat:    text("en_what").notNull().default(""),
  enWhere:   text("en_where").notNull().default(""),
  enAddress: text("en_address").notNull().default(""),
  enAdvice:  text("en_advice").notNull().default(""),
  enWarning: text("en_warning").notNull().default(""),

  ruTitle:   text("ru_title").notNull().default(""),
  ruWhat:    text("ru_what").notNull().default(""),
  ruWhere:   text("ru_where").notNull().default(""),
  ruAddress: text("ru_address").notNull().default(""),
  ruAdvice:  text("ru_advice").notNull().default(""),
  ruWarning: text("ru_warning").notNull().default(""),
});

export type Guide = typeof guides.$inferSelect;
export type Step  = typeof steps.$inferSelect;

export const newsPosts = sqliteTable("news_posts", {
  id:                 text("id").primaryKey(),
  slug:               text("slug").unique().notNull(),
  status:             text("status").notNull().default("draft"),
  category:           text("category").notNull().default("visa"),
  tagsJson:           text("tags_json").notNull().default("[]"),
  enTitle:            text("en_title").notNull().default(""),
  enSummary:          text("en_summary").notNull().default(""),
  enBody:             text("en_body").notNull().default(""),
  enSeoTitle:         text("en_seo_title").notNull().default(""),
  enMetaDescription:  text("en_meta_description").notNull().default(""),
  ruPublished:        integer("ru_published").notNull().default(0),
  ruTitle:            text("ru_title").notNull().default(""),
  ruSummary:          text("ru_summary").notNull().default(""),
  ruBody:             text("ru_body").notNull().default(""),
  ruSeoTitle:         text("ru_seo_title").notNull().default(""),
  ruMetaDescription:  text("ru_meta_description").notNull().default(""),
  sourceUrl:          text("source_url").notNull().default(""),
  sourceLabel:        text("source_label").notNull().default("media"),
  imagePath:          text("image_path").notNull().default(""),
  imageAlt:           text("image_alt").notNull().default(""),
  ruImageAlt:         text("ru_image_alt").notNull().default(""),
  datePublished:      text("date_published").notNull().default(""),
  dateUpdated:        text("date_updated").notNull().default(""),
  featuredHomepage:   integer("featured_homepage").notNull().default(0),
  featuredDigest:     integer("featured_digest").notNull().default(0),
  noindex:            integer("noindex").notNull().default(0),
  relatedGuideSlug:   text("related_guide_slug").notNull().default(""),
  relatedServiceSlug: text("related_service_slug").notNull().default(""),
  relatedToolSlug:    text("related_tool_slug").notNull().default(""),
  createdAt:          text("created_at").notNull(),
  updatedAt:          text("updated_at").notNull(),
});

export const eventsTable = sqliteTable("events", {
  id:               text("id").primaryKey(),
  slug:             text("slug").unique().notNull(),
  status:           text("status").notNull().default("draft"),
  category:         text("category").notNull().default("holiday"),
  colorType:        text("color_type").notNull().default("important-date"),
  tagsJson:         text("tags_json").notNull().default("[]"),
  enTitle:          text("en_title").notNull().default(""),
  enSummary:        text("en_summary").notNull().default(""),
  enBody:           text("en_body").notNull().default(""),
  enSeoTitle:       text("en_seo_title").notNull().default(""),
  enMetaDescription: text("en_meta_description").notNull().default(""),
  ruPublished:      integer("ru_published").notNull().default(0),
  ruTitle:          text("ru_title").notNull().default(""),
  ruSummary:        text("ru_summary").notNull().default(""),
  ruBody:           text("ru_body").notNull().default(""),
  ruSeoTitle:       text("ru_seo_title").notNull().default(""),
  ruMetaDescription: text("ru_meta_description").notNull().default(""),
  eventDateStart:   text("event_date_start").notNull().default(""),
  eventDateEnd:     text("event_date_end").notNull().default(""),
  dateConfidence:   text("date_confidence").notNull().default("confirmed"),
  year:             integer("year").notNull().default(0),
  sourceUrl:        text("source_url").notNull().default(""),
  featuredHomepage: integer("featured_homepage").notNull().default(0),
  featuredDigest:   integer("featured_digest").notNull().default(0),
  featuredCalendar: integer("featured_calendar").notNull().default(1),
  schemaEligible:   integer("schema_eligible").notNull().default(1),
  relatedGuideSlug: text("related_guide_slug").notNull().default(""),
  relatedNewsSlug:  text("related_news_slug").notNull().default(""),
  createdAt:        text("created_at").notNull(),
  updatedAt:        text("updated_at").notNull(),
});

export const calendarPages = sqliteTable("calendar_pages", {
  id:                 text("id").primaryKey(),
  slug:               text("slug").unique().notNull(),
  status:             text("status").notNull().default("draft"),
  calendarType:       text("calendar_type").notNull().default("monthly"),
  year:               integer("year").notNull().default(0),
  month:              integer("month"),
  enTitle:            text("en_title").notNull().default(""),
  enSummary:          text("en_summary").notNull().default(""),
  enBody:             text("en_body").notNull().default(""),
  enNotes:            text("en_notes").notNull().default(""),
  enSeoTitle:         text("en_seo_title").notNull().default(""),
  enMetaDescription:  text("en_meta_description").notNull().default(""),
  ruPublished:        integer("ru_published").notNull().default(0),
  ruTitle:            text("ru_title").notNull().default(""),
  ruSummary:          text("ru_summary").notNull().default(""),
  ruBody:             text("ru_body").notNull().default(""),
  ruNotes:            text("ru_notes").notNull().default(""),
  ruSeoTitle:         text("ru_seo_title").notNull().default(""),
  ruMetaDescription:  text("ru_meta_description").notNull().default(""),
  imagePath:          text("image_path").notNull().default(""),
  imageAlt:           text("image_alt").notNull().default(""),
  ruImageAlt:         text("ru_image_alt").notNull().default(""),
  datesJson:          text("dates_json").notNull().default("[]"),
  hasIslamicDates:    integer("has_islamic_dates").notNull().default(0),
  officialSourceUrl:  text("official_source_url").notNull().default(""),
  lastVerifiedDate:   text("last_verified_date").notNull().default(""),
  featuredHomepage:   integer("featured_homepage").notNull().default(0),
  createdAt:          text("created_at").notNull(),
  updatedAt:          text("updated_at").notNull(),
});

export type NewsPost     = typeof newsPosts.$inferSelect;
export type HubEvent     = typeof eventsTable.$inferSelect;
export type CalendarPage = typeof calendarPages.$inferSelect;
